name: Deploy PRD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render PRD Deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_PRD }}"
